language: c

matrix:
  include:
    - name: "build"
      install:
        - pushd $HOME
        - git clone https://github.com/samdoshi/avr32-toolchain-linux.git deps/avr32-toolchain-linux
        - cd deps/avr32-toolchain-linux
        - tar xvfz avr32-gnu-toolchain-3.4.3.820-linux.any.x86_64.tar.gz
        - mv avr32-gnu-toolchain-linux_x86_64 $HOME/avr32-tools
        - unzip avr32-headers-6.2.0.742.zip -d $HOME/avr32-tools/avr32/include
        - popd
      script:
        - cd module
        - PATH="$HOME/avr32-tools/bin:$PATH" make
        - cd ../simulator
        - make clean && make
        - cd ../tests
        - make clean && make test-travis
    - name: "format"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-format-7
      script:
        - export PATH="/usr/lib/llvm-7/bin:$PATH"
        - which clang-format
        - clang-format --version
        - find . -type f -name "*.c" -o -name "*.h" | xargs clang-format -style=file -i
        - if [[ $(git ls-files --modified) ]] ; then echo "Files not formatted:" && git diff && exit 1 ; else exit 0 ; fi
