["TO.TR"]
prototype_set = "TO.TR x y"
short = "sets the `TR` value for output `x` to `y` (0/1)"

["TO.TR.TOG"]
prototype_set = "TO.TR.TOG x"
short = "toggles the `TR` value for output `x`"

["TO.TR.PULSE"]
prototype_set = "TO.TR.PULSE x"
aliases = ["TO.TR.P"]
short = "pulses the `TR` value for output `x` for the duration set by `TO.TR.TIME/S/M`"

["TO.TR.PULSE.DIV"]
prototype_set = "TO.TR.PULSE.DIV x y"
aliases = ["TO.TR.P.DIV"]
short = "sets the clock division factor for `TR` output `x` to `y`"
description = """
The pulse divider will output one trigger pulse every `y` pulse commands. For example, setting the `DIV` factor to `2` like this:
```
TO.TR.P.DIV 1 2
```
Will cause every other `TO.TR.P 1` command to emit a pulse.

Reset it to one (`TO.TR.P.DIV 1 1`) or initialize the output (`TO.TR.INIT 1`) to return to the default behavior.
"""

["TO.TR.TIME"]
prototype_set = "TO.TR.TIME x y"
short = "sets the time for `TR.PULSE` on output `n`; `y` in milliseconds"

["TO.TR.TIME.S"]
prototype_set = "TO.TR.TIME.S x y"
short = "sets the time for `TR.PULSE` on output `n`; `y` in seconds"

["TO.TR.TIME.M"]
prototype_set = "TO.TR.TIME.M x y"
short = "sets the time for `TR.PULSE` on output `n`; `y` in minutes"

["TO.TR.WIDTH"]
prototype_set = "TO.TR.WIDTH x y"
short = "sets the time for `TR.PULSE` on output `n` based on the width of its current metronomic value; `y` in percentage (0-100)"
description = """
The actual time value for the trigger pulse when set by the `WIDTH` command is relative to the current value for `TO.TR.M`. Changes to `TO.TR.M` will change the duration of `TR.PULSE` when using the `WIDTH` mode to set its value. Values for `y` are set in percentage (0-100).

For example:

```
TO.TR.M 1 1000
TO.TR.WIDTH 1 50
```

The length of a `TR.PULSE` is now 500ms.

```
TO.TR.M 1 500
```

The length of a `TR.PULSE` is now 250ms. Note that you don't need to use the width command again as it automatically tracks the value for `TO.TR.M`.
"""

["TO.TR.POL"]
prototype_set = "TO.TR.POL x y"
short = "sets the polarity for `TR` output `n`"

["TO.TR.M.ACT"]
prototype_set = "TO.TR.M.ACT x y"
short = "sets the active status for the independent metronome for output `x` to `y` (`0`/`1`); default `0` (disabled)"
description = """
Each `TR` output has its own independent metronome that will execute a `TR.PULSE` at a specified interval. The `ACT` command enables (1) or disables (0) the metronome.
"""

["TO.TR.M"]
prototype_set = "TO.TR.M x y"
short = "sets the independent metronome interval for output `x` to `y` in milliseconds; default `1000`"

["TO.TR.M.S"]
prototype_set = "TO.TR.M.S x y"
short = "sets the independent metronome interval for output `x` to `y` in seconds; default `1`"

["TO.TR.M.M"]
prototype_set = "TO.TR.M.M x y"
short = "sets the independent metronome interval for output `x` to `y` in minutes"

["TO.TR.M.BPM"]
prototype_set = "TO.TR.M.BPM x y"
short = "sets the independent metronome interval for output `x` to `y` in Beats Per Minute"

["TO.TR.M.COUNT"]
prototype_set = "TO.TR.M.COUNT x y"
short = "sets the number of repeats before deactivating for output `x` to `y`; default `0` (infinity)"
description = """
This allows for setting a limit to the number of times `TO.TR.M` will `PULSE` when active before automatically disabling itself. For example, let's set it to pulse 5 times with 500ms between pulses:

```
TO.TR.M 1 500
TO.TR.M.COUNT 1 5
```

Now, each time we activate it, the metronome will pulse 5 times - each a half-second apart.

```
TO.TR.M.ACT 1 1
```

`PULSE` ... `PULSE` ... `PULSE` ... `PULSE` ... `PULSE`.

The metronome is now disabled after pulsing five times. If you call `ACT` again, it will emit five more pulses.

To reset, either set your `COUNT` to zero (`TO.TR.M.COUNT 1 0`) or call init on the output (`TO.TR.INIT 1 1`).
"""

["TO.TR.M.SYNC"]
prototype_set = "TO.TR.M.SYNC d"
short = "synchronizes the metronomes for device number `d` (1-8)"
description = """
This command causes the TXo at device `d` to synchronize all of its independent metronomes to the moment it receives the command. Each will then continue to pulse at its own independent `M` rate.
"""

["TO.CV"]
prototype_set = "TO.CV x"
short = "CV target output `x`; `y` values are bipolar (-16384 to +16383) and map to -10 to +10"

["TO.CV.SLEW"]
prototype_set = "TO.CV.SLEW x y"
short = "set the slew amount for output `x`; `y` in milliseconds"

["TO.CV.SLEW.S"]
prototype_set = "TO.CV.SLEW.S x y"
short = "set the slew amount for output `x`; `y` in seconds"

["TO.CV.SLEW.M"]
prototype_set = "TO.CV.SLEW.M x y"
short = "set the slew amount for output `x`; `y` in minutes"

["TO.CV.SET"]
prototype_set = "TO.CV.SET x y"
short = "set the CV for output `x` (ignoring `SLEW`); `y` values are bipolar (-16384 to +16383) and map to -10 to +10"

["TO.CV.OFF"]
prototype_set = "TO.CV.OFF x y"
short = "set the CV offset for output `x`; `y` values are added at the final stage"

["TO.CV.QT"]
prototype_set = "TO.CV.QT x y"
short = "CV target output `x`; `y` is quantized to output's current `CV.SCALE`"

["TO.CV.QT.SET"]
prototype_set = "TO.CV.QT.SET x y"
short = "set the CV for output `x` (ignoring `SLEW`); `y` is quantized to output's current `CV.SCALE`"

["TO.CV.N"]
prototype_set = "TO.CV.N x y"
short = "target the CV to note `y` for output `x`; `y` is indexed in the output's current `CV.SCALE`"

["TO.CV.N.SET"]
prototype_set = "TO.CV.N.SET x y"
short = "set the CV to note `y` for output `x`; `y` is indexed in the output's current `CV.SCALE` (ignoring `SLEW`)"

["TO.CV.SCALE"]
prototype_set = "TO.CV.SCALE x y"
short = "select scale # `y` for CV output `x`; scales listed in full description"
description = """
### Quantization Scales
0. Equal Temperament [DEFAULT]
1. 12-tone Pythagorean scale
2. Vallotti & Young scale (Vallotti version) also known as Tartini-Vallotti (1754)
3. Andreas Werckmeister's temperament III (the most famous one, 1681)
4. Wendy Carlos' Alpha scale with perfect fifth divided in nine
5. Wendy Carlos' Beta scale with perfect fifth divided by eleven
6. Wendy Carlos' Gamma scale with third divided by eleven or fifth by twenty
7. Carlos Harmonic & Ben Johnston's scale of 'Blues' from Suite f.micr.piano (1977) & David Beardsley's scale of 'Science Friction'
8. Carlos Super Just
9. Kurzweil "Empirical Arabic"
10. Kurzweil "Just with natural b7th", is Sauveur Just with 7/4
11. Kurzweil "Empirical Bali/Java Harmonic Pelog"
12. Kurzweil "Empirical Bali/Java Slendro, Siam 7"
13. Kurzweil "Empirical Tibetian Ceremonial"
14. Harry Partch's 43-tone pure scale
15. Partch's Indian Chromatic, Exposition of Monophony, 1933. 
16. Partch Greek scales from "Two Studies on Ancient Greek Scales" on black/white 
"""

["TO.OSC"]
prototype_set = "TO.OSC x y"
short = "targets oscillation for CV output `x` to `y` with the portamento rate determined by the `TO.OSC.SLEW` value; `y` is 1v/oct translated from the standard range (1-16384); a value of `0` disables oscillation; `CV` amplitude is used as the peak for oscillation and needs to be `> 0` for it to be perceivable"
description = """
Setting an `OSC` frequency greater than zero for a `CV` output will start that output oscillating. It will swing its voltage between to the current `CV` value and its polar opposite. For example:

```
TO.CV 1 V 5
TO.OSC 1 N 69
```

This will emit the audio-rate note A (at 440Hz) swinging from '+5V' to '-5V'. The `CV` value acts as an amplitude control. For example:

```
TO.CV.SLEW.M 1 1
TO.CV 1 V 10
```

This will cause the oscillations to gradually increase in amplitude from `5V` to `10V` over a period of one minute.

**IMPORANT:** if you do not set a `CV` value, the oscillator will not emit a signal.

If you want to go back to regular `CV` behavior, you need to set the oscillation frequency to zero. E.g. `TO.OSC 1 0`. You can also initialize the `CV` output with `TO.CV.INIT 1`, which resets all of its settings back to start-up default.

"""

["TO.OSC.SET"]
prototype_set = "TO.OSC.SET x y"
short = "set oscillation for CV output `x` to `y` (ignores `CV.OSC.SLEW`); `y` is 1v/oct translated from the standard range (1-16384); a value of `0` disables oscillation; `CV` amplitude is used as the peak for oscillation and needs to be `> 0` for it to be perceivable"

["TO.OSC.QT"]
prototype_set = "TO.OSC.QT x y"
short = "targets oscillation for CV output `x` to `y` with the portamento rate determined by the `TO.OSC.SLEW` value; `y` is 1v/oct translated from the standard range (1-16384) and quantized to current `OSC.SCALE`; a value of `0` disables oscillation; `CV` amplitude is used as the peak for oscillation and needs to be `> 0` for it to be perceivable"

["TO.OSC.QT.SET"]
prototype_set = "TO.OSC.QT.SET x y"
short = "set oscillation for CV output `x` to `y` (ignores `CV.OSC.SLEW`); `y` is 1v/oct translated from the standard range (1-16384) and quantized to current `OSC.SCALE`; a value of `0` disables oscillation; `CV` amplitude is used as the peak for oscillation and needs to be `> 0` for it to be perceivable"

["TO.OSC.N"]
prototype_set = "TO.OSC.N x y"
short = "targets oscillation for CV output `x` to note `y` with the portamento rate determined by the `TO.OSC.SLEW` value; see quantization scale reference for `y`; `CV` amplitude is used as the peak for oscillation and needs to be `> 0` for it to be perceivable"

["TO.OSC.N.SET"]
prototype_set = "TO.OSC.N.SET x y"
short = "sets oscillation for CV output `x` to note `y` (ignores `CV.OSC.SLEW`); see quantization scale reference for `y`; `CV` amplitude is used as the peak for oscillation and needs to be `> 0` for it to be perceivable"

["TO.OSC.FQ"]
prototype_set = "TO.OSC.FQ x y"
short = "targets oscillation for CV output `x` to frequency `y` with the portamento rate determined by the `TO.OSC.SLEW` value; `y` is in Hz; a value of `0` disables oscillation; `CV` amplitude is used as the peak for oscillation and needs to be `> 0` for it to be perceivable"

["TO.OSC.FQ.SET"]
prototype_set = "TO.OSC.FQ x y"
short = "sets oscillation for CV output `x` to frequency `y` (ignores `CV.OSC.SLEW`); `y` is in Hz; a value of `0` disables oscillation; `CV` amplitude is used as the peak for oscillation and needs to be `> 0` for it to be perceivable"

["TO.OSC.LFO"]
prototype_set = "TO.OSC.LFO x y"
short = "targets oscillation for CV output `x` to LFO frequency `y` with the portamento rate determined by the `TO.OSC.SLEW` value; `y` is in mHz (millihertz: 10^-3 Hz); a value of `0` disables oscillation; `CV` amplitude is used as the peak for oscillation and needs to be `> 0` for it to be perceivable"

["TO.OSC.LFO.SET"]
prototype_set = "TO.OSC.LFO.SET x y"
short = "sets oscillation for CV output `x` to LFO frequency `y` (ignores `CV.OSC.SLEW`); `y` is in mHz (millihertz: 10^-3 Hz); a value of `0` disables oscillation; `CV` amplitude is used as the peak for oscillation and needs to be `> 0` for it to be perceivable"

["TO.OSC.SCALE"]
prototype_set = "TO.OSC.SCALE x y"
short = "select scale # `y` for CV output `x`; scales listed in full description"
description = """
### Quantization Scales
0. Equal Temperament [DEFAULT]
1. 12-tone Pythagorean scale
2. Vallotti & Young scale (Vallotti version) also known as Tartini-Vallotti (1754)
3. Andreas Werckmeister's temperament III (the most famous one, 1681)
4. Wendy Carlos' Alpha scale with perfect fifth divided in nine
5. Wendy Carlos' Beta scale with perfect fifth divided by eleven
6. Wendy Carlos' Gamma scale with third divided by eleven or fifth by twenty
7. Carlos Harmonic & Ben Johnston's scale of 'Blues' from Suite f.micr.piano (1977) & David Beardsley's scale of 'Science Friction'
8. Carlos Super Just
9. Kurzweil "Empirical Arabic"
10. Kurzweil "Just with natural b7th", is Sauveur Just with 7/4
11. Kurzweil "Empirical Bali/Java Harmonic Pelog"
12. Kurzweil "Empirical Bali/Java Slendro, Siam 7"
13. Kurzweil "Empirical Tibetian Ceremonial"
14. Harry Partch's 43-tone pure scale
15. Partch's Indian Chromatic, Exposition of Monophony, 1933. 
16. Partch Greek scales from "Two Studies on Ancient Greek Scales" on black/white 
"""

["TO.OSC.CYC"]
prototype_set = "TO.OSC.CYC x y"
short = "targets the oscillator cycle length to `y` for CV output `x` with the portamento rate determined by the `TO.OSC.SLEW` value; `y` is in milliseconds"

["TO.OSC.CYC.SET"]
prototype_set = "TO.OSC.CYC.SET x y"
short = "sets the oscillator cycle length to `y` for CV output `x` (ignores `CV.OSC.SLEW`); `y` is in milliseconds"

["TO.OSC.CYC.S"]
prototype_set = "TO.OSC.CYC.S x y"
short = "targets the oscillator cycle length to `y` for CV output `x` with the portamento rate determined by the `TO.OSC.SLEW` value; `y` is in seconds"

["TO.OSC.CYC.S.SET"]
prototype_set = "TO.OSC.CYC.S.SET x y"
short = "sets the oscillator cycle length to `y` for CV output `x` (ignores `CV.OSC.SLEW`); `y` is in seconds"

["TO.OSC.CYC.M"]
prototype_set = "TO.OSC.CYC.M x y"
short = "targets the oscillator cycle length to `y` for CV output `x` with the portamento rate determined by the `TO.OSC.SLEW` value; `y` is in minutes"

["TO.OSC.CYC.M.SET"]
prototype_set = "TO.OSC.CYC.M.SET x y"
short = "sets the oscillator cycle length to `y` for CV output `x` (ignores `CV.OSC.SLEW`); `y` is in minutes"

["TO.OSC.WAVE"]
prototype_set = "TO.OSC.WAVE x y"
short = "set the waveform for output `x` to `y`; `y` values range `0-4999`; values translate to sine (0), triangle (1000), saw (2000), pulse (3000), or noise (4000); oscillator shape between values is a blend of the pure waveforms"

["TO.OSC.WIDTH"]
prototype_set = "TO.OSC.WIDTH x y"
short = "sets the width of the pulse wave on output `x` to `y`; `y` is a percentage of total width (0 to 100); only affects waveform `3000`"

["TO.OSC.SYNC"]
prototype_set = "TO.OSC.SYNC x"
short = "resets the phase of the oscillator on `CV` output `x` (relative to `TO.OSC.PHASE`)"

["TO.OSC.PHASE"]
prototype_set = "TO.OSC.PHASE x y"
short = "sets the phase offset of the oscillator on CV output `x` to `y` (0 to 16383); `y` is the range of one cycle"

["TO.OSC.RECT"]
prototype_set = "TO.OSC.RECT x y"
short = "rectifies the polarity of the oscillator for output `x` to `y`; range for `y` is -2 to 2; default is 0 (no rectification); 1 & -1 are partial rectification - omitting all values on the other side of the sign; 2 & -2 are full rectification - inverting values from the other pole"
description = """
The rectification command performs a couple of levels of rectification based on how you have it set. The following values for `y` work as follows:
* `y = 2`: "full-positive" - inverts negative values, making them positive
* `y = 1`: "half-positive" - omits all negative values (values below zero are set to zero)
* `y = 0`: no rectification (default)
* `y = -1`: "half-negative" - omits all positive values (values above zero are set to zero)
* `y = -2`: "full-negative" - inverts positive values, making them negative
"""

["TO.OSC.SLEW"]
prototype_set = "TO.OSC.SLEW x y"
short = "sets the frequency slew time (portamento) for the oscillator on CV output `x` to `y`; `y` in milliseconds"
description = """
This parameter acts as a frequency slew for the targeted `CV` output. It allows you to gradually slide from one frequency to another, creating a portamento like effect. It is also great for smoothing transitions between different `LFO` rates on the oscillator. For example:

```
TO.CV 1 V 5
TO.OSC.SLEW 1 30000
TO.OSC.LFO.SET 1 1000
TO.OSC.LFO 1 100
```

This will start an LFO on `CV 1` with a rate of 1000mHz. Then, over the next 30 seconds, it will gradually decrease in rate to 100mHz.
"""

["TO.OSC.SLEW.S"]
prototype_set = "TO.OSC.SLEW.S x y"
short = "sets the frequency slew time (portamento) for the oscillator on CV output `x` to `y`; `y` in seconds"

["TO.OSC.SLEW.M"]
prototype_set = "TO.OSC.SLEW.M x y"
short = "sets the frequency slew time (portamento) for the oscillator on CV output `x` to `y`; `y` in minutes"

["TO.ENV.ACT"]
prototype_set = "TO.ENV.ACT x y"
short = "activates/deactivates the AD envelope generator for the CV output `x`; `y` turns the envelope generator off (0 - default) or on (1);  `CV` amplitude is used as the peak for the envelope and needs to be `> 0` for the envelope to be perceivable"
description = """
This setting activates (1) or deactivates (0) the envelope generator on `CV` output `y`. The envelope generator is dependent on the current voltage setting for the output. Upon activation, the targeted output will go to zero. Then, when triggered (`TO.ENV.TRIG`), it will ramp the voltage from zero to the currently set peak voltage (`TO.CV`) over the attack time (`TO.ENV.ATT`) and then decay back to zero over the decay time (`TO.ENV.DEC`). For example:

```
TO.CV.SET 1 V 8
TO.ENV.ACT 1 1
TO.ENV.ATT.S 1 1
TO.ENV.DEC.S 1 30
```

This will initialize the `CV 1` output to have an envelope that will ramp to `+8V` over one second and decay back to zero over thirty seconds. To trigger the envelope, you need to send the trigger command `TO.ENV.TRIG 1`. Envelopes currently re-trigger from the start of the cycle.

To return your `CV` output to normal function, either deactivate the envelope (`TO.ENV.ACT 1 0`) or reinitialize the output (`TO.CV.INIT 1`).
"""

["TO.ENV.TRIG"]
prototype_set = "TO.ENV.TRIG x"
short = "triggers the envelope at `CV` output `x` to cycle;  `CV` amplitude is used as the peak for the envelope and needs to be `> 0` for the envelope to be perceivable"

["TO.ENV.ATT"]
prototype_set = "TO.ENV.ATT x y"
short = "set the envelope attack time to `y` for `CV` output `x`; `y` in milliseconds (default 12 ms)"

["TO.ENV.ATT.S"]
prototype_set = "TO.ENV.ATT.S x y"
short = "set the envelope attack time to `y` for `CV` output `x`; `y` in seconds"

["TO.ENV.ATT.M"]
prototype_set = "TO.ENV.ATT.M x y"
short = "set the envelope attack time to `y` for `CV` output `x`; `y` in minutes"

["TO.ENV.DEC"]
prototype_set = "TO.ENV.DEC x y"
short = "set the envelope decay time to `y` for `CV` output `x`; `y` in milliseconds (default 250 ms)"

["TO.ENV.DEC.S"]
prototype_set = "TO.ENV.DEC.S x y"
short = "set the envelope decay time to `y` for `CV` output `x`; `y` in seconds"

["TO.ENV.DEC.M"]
prototype_set = "TO.ENV.DEC.M x y"
short = "set the envelope decay time to `y` for `CV` output `x`; `y` in minutes"

["TO.TR.INIT"]
prototype_set = "TO.TR.INIT x"
short = "initializes `TR` output `x` back to the default boot settings and behaviors; neutralizes metronomes, dividers, pulse counters, etc."

["TO.CV.INIT"]
prototype_set = "TO.CV.INIT x"
short = "initializes `CV` output `x` back to the default boot settings and behaviors; neutralizes offsets, slews, envelopes, oscillation, etc."

["TO.INIT"]
prototype_set = "TO.INIT d"
short = "initializes all of the `TR` and `CV` outputs for device number `d` (1-8)"
